from tkinter import *
from pygame import mixer


# Board with other miscellaneous sounds
class Misc:

    def __init__(self, window):
        frame = Frame(window)
        frame.pack()

        yee = mixer.Sound('Sounds\Misc\Yee.wav')
        yee2 = mixer.Sound('Sounds\Misc\Yee2.wav')
        chilis = mixer.Sound('Sounds\Misc\Chilis.wav')
        xp = mixer.Sound('Sounds\Misc\Windows.wav')
        whisperW = mixer.Sound('Sounds\Misc\Wa\WarioWhisper.wav')
        whisperWL = mixer.Sound('Sounds\Misc\Wa\WaluigiWhisper.wav')
        poopWa = mixer.Sound('Sounds\Misc\Wa\PoopWa.wav')
        coolWa = mixer.Sound('Sounds\Misc\Wa\CoolWas.wav')
        fancyWa = mixer.Sound('Sounds\Misc\Wa\FancyWa.wav')
        angryWa = mixer.Sound('Sounds\Misc\Wa\AngryWa.wav')
        luigiWa = mixer.Sound('Sounds\Misc\Wa\LuigiWa.wav')
        memes = mixer.Sound('Sounds\Misc\memes.wav')
        just1 = mixer.Sound('Sounds\Misc\Just One\JustOne1.wav')
        just2 = mixer.Sound('Sounds\Misc\Just One\JustOne2.wav')
        just3 = mixer.Sound('Sounds\Misc\Just One\JustOne3.wav')
        just4 = mixer.Sound('Sounds\Misc\Just One\JustOne4.wav')
        just5 = mixer.Sound('Sounds\Misc\Just One\JustOne5.wav')
        just6 = mixer.Sound('Sounds\Misc\Just One\JustOne6.wav')
        friends = mixer.Sound('Sounds\Misc\Just One\FriendsDisappoint.wav')
        weird = mixer.Sound('Sounds\Misc\Just One\WeirdQuestion.wav')
        touches = mixer.Sound('Sounds\Misc\Just One\Touches.wav')
        asuh = mixer.Sound('Sounds\Misc\Suh Dude\AsuhDude.wav')
        dude = mixer.Sound('Sounds\Misc\Suh Dude\DudeSuh.wav')
        fuckBees = mixer.Sound('Sounds\Misc\FuckBees\FuckBees.wav')
        bees = mixer.Sound('Sounds\Misc\FuckBees\Bees.wav')
        fuck = mixer.Sound('Sounds\Misc\FuckBees\Fuck.wav')
        krusty = mixer.Sound('Sounds\Misc\KrustyKrab.wav')
        eff = mixer.Sound('Sounds\Misc\Street Magic\WhatTheEff.wav')
        sueYou = mixer.Sound('Sounds\Misc\Street Magic\SueYou.wav')
        bodies = mixer.Sound('Sounds\Misc\Street Magic\ShitOnOurBodies.wav')
        demon = mixer.Sound('Sounds\Misc\Street Magic\FuckingDemon.wav')
        cheezit1 = mixer.Sound('Sounds\Misc\Street Magic 2\Cheezits1.wav')
        cheezit2 = mixer.Sound('Sounds\Misc\Street Magic 2\Cheezits2.wav')
        # ----------------------------------------------------------------------

        self.title = Label(frame, text='Miscellaneous Sounds')
        self.title.grid(row=0, columnspan=5)

        self.yee1Btn = Button(frame, text='Yee 1', command=yee.play)
        self.yee2Btn = Button(frame, text='Yee 2', command=yee2.play)
        self.chilisBtn = Button(frame, text="Chili's", command=chilis.play)
        self.xpBtn = Button(frame, text='Windows XP', command=xp.play)
        self.whisperWBtn = Button(frame, text='Wario Soft Wa', command=whisperW.play)
        self.whisperWLBtn = Button(frame, text='Waluigi Soft Wa', command=whisperWL.play)
        self.poopWaBtn = Button(frame, text='Poop Wa', command=poopWa.play)
        self.coolWaBtn = Button(frame, text='Cool Was', command=coolWa.play)
        self.fancyWaBtn = Button(frame, text='Fancy Wa', command=fancyWa.play)
        self.angryWaBtn = Button(frame, text='Angry Wa', command=angryWa.play)
        self.luigiWaBtn = Button(frame, text='Luigi Wa', command=luigiWa.play)
        self.memesBtn = Button(frame, text='I Love Memes', command=memes.play)
        self.just1Btn = Button(frame, text='Just One 1', command=just1.play)
        self.just2Btn = Button(frame, text='Just One 2', command=just2.play)
        self.just3Btn = Button(frame, text='Just One 3', command=just3.play)
        self.just4Btn = Button(frame, text='Just One 4', command=just4.play)
        self.just5Btn = Button(frame, text='Just One 5', command=just5.play)
        self.just6Btn = Button(frame, text='Just One 6', command=just6.play)
        self.friendsBtn = Button(frame, text='Friends Disappoint Me', command=friends.play)
        self.weirdBtn = Button(frame, text='Weird Question?', command=weird.play)
        self.touchesBtn = Button(frame, text='When She Touches Me', command=touches.play)
        self.asuhBtn = Button(frame, text='Asuh Dude', command=asuh.play)
        self.dudeBtn = Button(frame, text='Dude Suh', command=dude.play)
        self.fuckBeesBtn = Button(frame, text='Fuck Bees', command=fuckBees.play)
        self.beesBtn = Button(frame, text='Bees', command=bees.play)
        self.fuckBtn = Button(frame, text='Fuck', command=fuck.play)
        self.krustyBtn = Button(frame, text='Krusty Krab', command=krusty.play)
        self.effBtn = Button(frame, text='What The Eff', command=eff.play)
        self.sueYouBtn = Button(frame, text='Ace Of Clubs In My Ass', command=sueYou.play)
        self.bodiesBtn = Button(frame, text='Stop Putting Shit On Our Bodies', command=bodies.play)
        self.demonBtn = Button(frame, text='Fucking Demon', command=demon.play)
        self.cheezit1Btn = Button(frame, text='Cheezits 1', command=cheezit1.play)
        self.cheezit2Btn = Button(frame, text='Cheezits 2', command=cheezit2.play)
        # ----------------------------------------------------------------------

        self.yee1Btn.grid(row=1, column=0)
        self.yee2Btn.grid(row=1, column=1)
        self.chilisBtn.grid(row=1, column=2)
        self.xpBtn.grid(row=1, column=3)
        self.whisperWBtn.grid(row=1, column=4)
        self.whisperWLBtn.grid(row=2, column=0)
        self.poopWaBtn.grid(row=2, column=1)
        self.coolWaBtn.grid(row=2, column=2)
        self.fancyWaBtn.grid(row=2, column=3)
        self.angryWaBtn.grid(row=2, column=4)
        self.luigiWaBtn.grid(row=3, column=0)
        self.memesBtn.grid(row=3, column=1)
        self.just1Btn.grid(row=3, column=2)
        self.just2Btn.grid(row=3, column=3)
        self.just3Btn.grid(row=3, column=4)
        self.just4Btn.grid(row=4, column=0)
        self.just5Btn.grid(row=4, column=1)
        self.just6Btn.grid(row=4, column=2)
        self.friendsBtn.grid(row=4, column=3)
        self.weirdBtn.grid(row=4, column=4)
        self.touchesBtn.grid(row=5, column=0)
        self.asuhBtn.grid(row=5, column=1)
        self.dudeBtn.grid(row=5, column=2)
        self.fuckBeesBtn.grid(row=5, column=3)
        self.beesBtn.grid(row=5, column=4)
        self.fuckBtn.grid(row=6, column=0)
        self.krustyBtn.grid(row=6, column=1)
        self.effBtn.grid(row=6, column=2)
        self.sueYouBtn.grid(row=6, column=3)
        self.bodiesBtn.grid(row=6, column=4)
        self.demonBtn.grid(row=7, column=1)
        self.cheezit1Btn.grid(row=7, column=2)
        self.cheezit2Btn.grid(row=7, column=3)
        # ----------------------------------------------------------------------